### ISSUE TITLE
Can not execute 'start-crawl': Exec format error

### ISSUE THREAD

**Issue by rothanachoun** [elacuesta/scrapy-playwright-cloud-example#4]
I have deployed successfully but I got this error "Can not execute 'start-crawl': Exec format error" when trying to run a spider.

**Comment by elacuesta** [comment]
I cannot reproduce. I've followed the steps from the readme and the spider runs correctly:

```
shub image upload
shub schedule headers
```

![Screenshot at 2024-07-14 20-16-46](https://github.com/user-attachments/assets/0f223ca2-6425-4d61-8924-7656a0f6af2f)

What exactly have you tried?

**Comment by rothanachoun** [comment]
I followed the same steps as you did (according to the readme), but strangely, I encountered an error. So there must be something wrong with my machine then. 
Thank you for your response!
